; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 2h                          ; CFG: mov 10 -> mov 2; imul 5
    nop                                  ; CFG dead code (renamed)
    imul rcx, 5h
    sub rax, rax                         ; CFG: xor -> sub
    xor rdx, rdx                         ; CFG: mov 1 -> xor; inc
    inc rdx
fib_loop:
    add rax, rdx
    xchg rax, rdx
    nop                                  ; CFG dead code (renamed)
    dec rcx
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    mov r15, r15                         ; CFG dead code: nop equiv (renamed)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
