; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    push 0ah                             ; CFG: mov 10 -> push; pop
    pop rcx
    xor rax, rax                         ; f0 = 0
    xor rdx, rdx                         ; CFG: mov 1 -> xor; inc
    inc rdx
fib_loop:
    add rax, rdx                         ; CFG: reordered block
    xchg rax, rdx
    dec rcx
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    push r11                             ; CFG dead code: push/pop (renamed)
    pop r11                              ; CFG dead code: push/pop (renamed)
    call ExitProcess                     ; CFG: reordered block
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
