; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 0ah                         ; n = 10
    and rax, 0h                          ; CFG: xor -> and 0
    xor rdx, rdx                         ; CFG: mov 1 -> xor; inc
    mov r15, r15                         ; CFG dead code: nop equiv (renamed)
    inc rdx
fib_loop:
    add rax, rdx
    push rax                             ; CFG: xchg -> push/mov/pop
    push r11                             ; CFG dead code: push/pop (renamed)
    pop r11                              ; CFG dead code: push/pop (renamed)
    mov rax, rdx
    pop rdx
    sub rcx, 1h                          ; CFG: dec -> sub 1
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
