; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 0ah                         ; n = 10
    and rax, 0h                          ; CFG: xor -> and 0
    mov rdx, 1h                          ; f1 = 1
fib_loop:
    add rax, rdx                         ; CFG: reordered block
    lea r14, [r14]                       ; CFG dead code: lea nop (renamed)
    push rax                             ; CFG: xchg -> push/mov/pop
    nop                                  ; CFG dead code (renamed)
    mov rax, rdx
    pop rdx
    dec rcx
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess                     ; CFG: reordered block
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
