; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 0ah                         ; n = 10
    sub rax, rax                         ; CFG: xor -> sub
    xor rdx, rdx                         ; CFG: mov 1 -> xor; inc
    nop                                  ; CFG dead code (renamed)
    inc rdx
    mov r13, r13                         ; CFG dead code: nop equiv (renamed)
fib_loop:
    add rax, rdx
    xchg rax, rdx
    dec rcx
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    mov r9, r9                           ; CFG dead code: nop equiv (renamed)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
