; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 0ah                         ; n = 10
    sub rax, rax                         ; CFG: xor -> sub
    push r15                             ; CFG dead code: push/pop (renamed)
    pop r15                              ; CFG dead code: push/pop (renamed)
    mov rdx, 1h                          ; f1 = 1
    push r13                             ; CFG dead code: push/pop (renamed)
    pop r13                              ; CFG dead code: push/pop (renamed)
fib_loop:
    add rax, rdx                         ; CFG: reordered block
    xchg rax, rdx
    sub rcx, 1h                          ; CFG: dec -> sub 1
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess                     ; CFG: reordered block
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
