; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 5h                          ; CFG: mov 10 -> mov 5; add 5
    add rcx, 5h
    and rax, 0h                          ; CFG: xor -> and 0
    push 1h                              ; CFG: mov 1 -> push; pop
    lea r14, [r14]                       ; CFG dead code: lea nop (renamed)
    pop rdx
fib_loop:
    add rax, rdx                         ; CFG: reordered block
    xchg rax, rdx
    dec rcx
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess                     ; CFG: reordered block
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
