; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    push 0ah                             ; CFG: mov 10 -> push; pop
    pop rcx
    sub rax, rax                         ; CFG: xor -> sub
    nop                                  ; CFG dead code (renamed)
    push 1h                              ; CFG: mov 1 -> push; pop
    pop rdx
fib_loop:
    add rax, rdx                         ; CFG: reordered block
    push rax                             ; CFG: xchg -> push/mov/pop
    mov r15, r15                         ; CFG dead code: nop equiv (renamed)
    mov rax, rdx
    pop rdx
    dec rcx
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess                     ; CFG: reordered block
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
