; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 5h                          ; CFG: mov 10 -> mov 5; add 5
    mov r9, r9                           ; CFG dead code: nop equiv (renamed)
    add rcx, 5h
    and rax, 0h                          ; CFG: xor -> and 0
    xor rdx, rdx                         ; CFG: mov 1 -> xor; inc
    lea r12, [r12]                       ; CFG dead code: lea nop (renamed)
    inc rdx
    push r12                             ; CFG dead code: push/pop (renamed)
    pop r12                              ; CFG dead code: push/pop (renamed)
fib_loop:
    add rax, rdx
    nop                                  ; CFG dead code (renamed)
    xchg rax, rdx
    dec rcx
    jnz fib_loop
    nop                                  ; CFG dead code (renamed)
    mov rcx, rax                         ; exit code = fib(10)
    push r9                              ; CFG dead code: push/pop (renamed)
    pop r9                               ; CFG dead code: push/pop (renamed)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
