; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    push 0ah                             ; CFG: mov 10 -> push; pop
    pop rcx
    and rax, 0h                          ; CFG: xor -> and 0
    push 1h                              ; CFG: mov 1 -> push; pop
    push r10                             ; CFG dead code: push/pop (renamed)
    pop r10                              ; CFG dead code: push/pop (renamed)
    pop rdx
fib_loop:
    add rax, rdx
    xchg rax, rdx
    dec rcx
    jnz fib_loop
    mov r10, r10                         ; CFG dead code: nop equiv (renamed)
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
