; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 5h                          ; CFG: mov 10 -> mov 5; add 5
    nop                                  ; CFG dead code (renamed)
    add rcx, 5h
    and rax, 0h                          ; CFG: xor -> and 0
    mov rdx, 1h                          ; f1 = 1
fib_loop:
    add rax, rdx                         ; CFG: reordered block
    lea r13, [r13]                       ; CFG dead code: lea nop (renamed)
    push rax                             ; CFG: xchg -> push/mov/pop
    mov rax, rdx
    mov r8, r8                           ; CFG dead code: nop equiv (renamed)
    pop rdx
    nop                                  ; CFG dead code (renamed)
    sub rcx, 1h                          ; CFG: dec -> sub 1
    jnz fib_loop
    push r14                             ; CFG dead code: push/pop (renamed)
    pop r14                              ; CFG dead code: push/pop (renamed)
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess                     ; CFG: reordered block
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
