; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 0ah                         ; n = 10
    nop                                  ; CFG dead code (renamed)
    xor rax, rax                         ; f0 = 0
    push 1h                              ; CFG: mov 1 -> push; pop
    pop rdx
fib_loop:
    add rax, rdx
    xchg rax, rdx
    dec rcx
    jnz fib_loop
    push r11                             ; CFG dead code: push/pop (renamed)
    pop r11                              ; CFG dead code: push/pop (renamed)
    mov rcx, rax                         ; exit code = fib(10)
    lea r12, [r12]                       ; CFG dead code: lea nop (renamed)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
