; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    push 0ah                             ; CFG: mov 10 -> push; pop
    pop rcx
    sub rax, rax                         ; CFG: xor -> sub
    lea r14, [r14]                       ; CFG dead code: lea nop (renamed)
    mov rdx, 1h                          ; f1 = 1
    push r12                             ; CFG dead code: push/pop (renamed)
    pop r12                              ; CFG dead code: push/pop (renamed)
fib_loop:
    add rax, rdx
    xchg rax, rdx
    lea r13, [r13]                       ; CFG dead code: lea nop (renamed)
    dec rcx
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    nop                                  ; CFG dead code (renamed)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
