; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 0ah                         ; n = 10
    nop                                  ; CFG dead code (renamed)
    and rax, 0h                          ; CFG: xor -> and 0
    mov rdx, 1h                          ; f1 = 1
fib_loop:
    add rax, rdx
    mov r11, r11                         ; CFG dead code: nop equiv (renamed)
    push rax                             ; CFG: xchg -> push/mov/pop
    mov rax, rdx
    pop rdx
    sub rcx, 1h                          ; CFG: dec -> sub 1
    jnz fib_loop
    nop                                  ; CFG dead code (renamed)
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
