; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 5h                          ; CFG: mov 10 -> mov 5; add 5
    add rcx, 5h
    and rax, 0h                          ; CFG: xor -> and 0
    xor rdx, rdx                         ; CFG: mov 1 -> xor; inc
    inc rdx
    nop                                  ; CFG dead code (renamed)
fib_loop:
    add rax, rdx
    push rax                             ; CFG: xchg -> push/mov/pop
    nop                                  ; CFG dead code (renamed)
    mov rax, rdx
    mov r12, r12                         ; CFG dead code: nop equiv (renamed)
    pop rdx
    sub rcx, 1h                          ; CFG: dec -> sub 1
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
