; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    push 0ah                             ; CFG: mov 10 -> push; pop
    pop rcx
    sub rax, rax                         ; CFG: xor -> sub
    mov rdx, 1h                          ; f1 = 1
fib_loop:
    add rax, rdx
    xchg rax, rdx
    push r15                             ; CFG dead code: push/pop (renamed)
    pop r15                              ; CFG dead code: push/pop (renamed)
    sub rcx, 1h                          ; CFG: dec -> sub 1
    jnz fib_loop
    lea r8, [r8]                         ; CFG dead code: lea nop (renamed)
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
