; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 0ah                         ; n = 10
    sub rax, rax                         ; CFG: xor -> sub
    push 1h                              ; CFG: mov 1 -> push; pop
    mov r13, r13                         ; CFG dead code: nop equiv (renamed)
    pop rdx
fib_loop:
    add rax, rdx
    lea r15, [r15]                       ; CFG dead code: lea nop (renamed)
    xchg rax, rdx
    sub rcx, 1h                          ; CFG: dec -> sub 1
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
