; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 2h                          ; CFG: mov 10 -> mov 2; imul 5
    imul rcx, 5h
    sub rax, rax                         ; CFG: xor -> sub
    xor rdx, rdx                         ; CFG: mov 1 -> xor; inc
    inc rdx
    nop                                  ; CFG dead code (renamed)
fib_loop:
    add rax, rdx                         ; CFG: reordered block
    push rax                             ; CFG: xchg -> push/mov/pop
    mov rax, rdx
    pop rdx
    nop                                  ; CFG dead code (renamed)
    sub rcx, 1h                          ; CFG: dec -> sub 1
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess                     ; CFG: reordered block
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
