; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    push 0ah                             ; CFG: mov 10 -> push; pop
    lea r10, [r10]                       ; CFG dead code: lea nop (renamed)
    pop rcx
    xor rax, rax                         ; f0 = 0
    push 1h                              ; CFG: mov 1 -> push; pop
    pop rdx
    nop                                  ; CFG dead code (renamed)
fib_loop:
    add rax, rdx
    push r13                             ; CFG dead code: push/pop (renamed)
    pop r13                              ; CFG dead code: push/pop (renamed)
    xchg rax, rdx
    dec rcx
    jnz fib_loop
    mov r10, r10                         ; CFG dead code: nop equiv (renamed)
    mov rcx, rax                         ; exit code = fib(10)
    lea r15, [r15]                       ; CFG dead code: lea nop (renamed)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
