; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 0ah                         ; n = 10
    xor rax, rax                         ; f0 = 0
    nop                                  ; CFG dead code (renamed)
    xor rdx, rdx                         ; CFG: mov 1 -> xor; inc
    inc rdx
fib_loop:
    add rax, rdx                         ; CFG: reordered block
    xchg rax, rdx
    sub rcx, 1h                          ; CFG: dec -> sub 1
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    lea r12, [r12]                       ; CFG dead code: lea nop (renamed)
    call ExitProcess                     ; CFG: reordered block
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
