; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    push 0ah                             ; CFG: mov 10 -> push; pop
    nop                                  ; CFG dead code (renamed)
    pop rcx
    xor rax, rax                         ; f0 = 0
    xor rdx, rdx                         ; CFG: mov 1 -> xor; inc
    inc rdx
fib_loop:
    add rax, rdx                         ; CFG: reordered block
    mov r15, r15                         ; CFG dead code: nop equiv (renamed)
    push rax                             ; CFG: xchg -> push/mov/pop
    mov rax, rdx
    pop rdx
    sub rcx, 1h                          ; CFG: dec -> sub 1
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess                     ; CFG: reordered block
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
