; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 5h                          ; CFG: mov 10 -> mov 5; add 5
    push r14                             ; CFG dead code: push/pop (renamed)
    pop r14                              ; CFG dead code: push/pop (renamed)
    add rcx, 5h
    sub rax, rax                         ; CFG: xor -> sub
    push 1h                              ; CFG: mov 1 -> push; pop
    pop rdx
fib_loop:
    add rax, rdx
    push rax                             ; CFG: xchg -> push/mov/pop
    mov rax, rdx
    pop rdx
    dec rcx
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    lea r15, [r15]                       ; CFG dead code: lea nop (renamed)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
