; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    push 0ah                             ; CFG: mov 10 -> push; pop
    push r13                             ; CFG dead code: push/pop (renamed)
    pop r13                              ; CFG dead code: push/pop (renamed)
    pop rcx
    xor rax, rax                         ; f0 = 0
    push 1h                              ; CFG: mov 1 -> push; pop
    pop rdx
    mov r9, r9                           ; CFG dead code: nop equiv (renamed)
fib_loop:
    add rax, rdx
    lea r12, [r12]                       ; CFG dead code: lea nop (renamed)
    push rax                             ; CFG: xchg -> push/mov/pop
    mov rax, rdx
    pop rdx
    mov r11, r11                         ; CFG dead code: nop equiv (renamed)
    dec rcx
    jnz fib_loop
    nop                                  ; CFG dead code (renamed)
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
