; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 5h                          ; CFG: mov 10 -> mov 5; add 5
    add rcx, 5h
    nop                                  ; CFG dead code (renamed)
    sub rax, rax                         ; CFG: xor -> sub
    push r12                             ; CFG dead code: push/pop (renamed)
    pop r12                              ; CFG dead code: push/pop (renamed)
    xor rdx, rdx                         ; CFG: mov 1 -> xor; inc
    inc rdx
    nop                                  ; CFG dead code (renamed)
fib_loop:
    add rax, rdx
    mov r15, r15                         ; CFG dead code: nop equiv (renamed)
    push rax                             ; CFG: xchg -> push/mov/pop
    mov rax, rdx
    pop rdx
    push r14                             ; CFG dead code: push/pop (renamed)
    pop r14                              ; CFG dead code: push/pop (renamed)
    sub rcx, 1h                          ; CFG: dec -> sub 1
    jnz fib_loop
    nop                                  ; CFG dead code (renamed)
    mov rcx, rax                         ; exit code = fib(10)
    push r14                             ; CFG dead code: push/pop (renamed)
    pop r14                              ; CFG dead code: push/pop (renamed)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
