; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 0ah                         ; n = 10
    sub rax, rax                         ; CFG: xor -> sub
    push 1h                              ; CFG: mov 1 -> push; pop
    pop rdx
    push r12                             ; CFG dead code: push/pop (renamed)
    pop r12                              ; CFG dead code: push/pop (renamed)
fib_loop:
    add rax, rdx
    nop                                  ; CFG dead code (renamed)
    xchg rax, rdx
    dec rcx
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
