; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 5h                          ; CFG: mov 10 -> mov 5; add 5
    add rcx, 5h
    push r13                             ; CFG dead code: push/pop (renamed)
    pop r13                              ; CFG dead code: push/pop (renamed)
    xor rax, rax                         ; f0 = 0
    mov rdx, 1h                          ; f1 = 1
    mov r12, r12                         ; CFG dead code: nop equiv (renamed)
fib_loop:
    add rax, rdx
    lea r12, [r12]                       ; CFG dead code: lea nop (renamed)
    push rax                             ; CFG: xchg -> push/mov/pop
    mov rax, rdx
    pop rdx
    dec rcx
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    nop                                  ; CFG dead code (renamed)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
