; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 2h                          ; CFG: mov 10 -> mov 2; imul 5
    imul rcx, 5h
    lea r14, [r14]                       ; CFG dead code: lea nop (renamed)
    and rax, 0h                          ; CFG: xor -> and 0
    push 1h                              ; CFG: mov 1 -> push; pop
    pop rdx
    mov r9, r9                           ; CFG dead code: nop equiv (renamed)
fib_loop:
    add rax, rdx
    push rax                             ; CFG: xchg -> push/mov/pop
    mov rax, rdx
    pop rdx
    sub rcx, 1h                          ; CFG: dec -> sub 1
    jnz fib_loop
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
