; CFG-based Metamorphic variant generated by Rust CFG Transformation Engine
; Bachelor's Thesis: Design and Evaluation of a Rust Based Metamorphic Malware Transformation Engine

extern ExitProcess : proc

.code
main PROC
    sub rsp, 28h                         ; 32 bytes shadow space + alignment
    mov rcx, 2h                          ; CFG: mov 10 -> mov 2; imul 5
    push r13                             ; CFG dead code: push/pop (renamed)
    pop r13                              ; CFG dead code: push/pop (renamed)
    imul rcx, 5h
    sub rax, rax                         ; CFG: xor -> sub
    nop                                  ; CFG dead code (renamed)
    mov rdx, 1h                          ; f1 = 1
fib_loop:
    add rax, rdx
    xchg rax, rdx
    dec rcx
    jnz fib_loop
    push r8                              ; CFG dead code: push/pop (renamed)
    pop r8                               ; CFG dead code: push/pop (renamed)
    mov rcx, rax                         ; exit code = fib(10)
    call ExitProcess
    add rsp, 28h                         ; (never reached, but ABI-correct)
main ENDP
END
